version: 1.0.{build}
environment:
  NO_EXTERNAL_TESTS: 1
  matrix:
  - TOXENV: py27
  - TOXENV: py34
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37
install:
- cmd: pip install tox
test_script:
- cmd: tox