version: 1.0.{build}
image:
  - Visual Studio 2017
  - ubuntu1804
environment:
  NO_EXTERNAL_TESTS: 1
  matrix:
  - TOXENV: py27
  - TOXENV: py34
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37

for:
-
  matrix:
    only:
      - image: Visual Studio 2017

  environment:
    GPGBINARY: gpg2

  install:
  - cmd: appveyor-retry choco install gpg4win
  - cmd: refreshenv
  - ps: |
          $path = [Environment]::GetEnvironmentVariable("path", "machine")
          $newPath = $path + ";C:\Program Files (x86)\GnuPG\bin;"
          [Environment]::SetEnvironmentVariable("path", $newPath, "machine")
  - cmd: pip install tox

install:
- cmd: pip install tox
build: off
test_script:
- cmd: tox -c av-tox.ini
